# Generated by Django 5.2.4 on 2025-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_n_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
    ]
