# Generated by Django 5.2.4 on 2025-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False)),
                ('event_or_cause_id', models.UUIDField(db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_id', models.UUIDField(db_index=True, editable=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
