# Generated by Django 5.2.4 on 2025-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
