# Generated by Django 5.2.4 on 2025-07-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_payment_method',
        ),
    ]
