# Generated by Django 5.2.4 on 2025-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='causes',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='causes',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
