# Generated by Django 5.2.4 on 2025-07-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_remove_causes_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='causes',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='under_review', max_length=20),
        ),
    ]
