# Generated by Django 5.2.4 on 2025-07-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
