# Generated by Django 5.2.4 on 2025-07-24 01:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedReportData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('donations', 'Donations'), ('users', 'Users'), ('causes', 'Causes')], max_length=50)),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('report_type', 'generated_at')},
            },
        ),
    ]
