# Generated by Django 5.2.4 on 2025-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_code',
            field=models.CharField(blank=True, help_text='Code of the recipient for future transactions.', max_length=100, null=True),
        ),
    ]
