# Generated by Django 5.2.4 on 2025-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_n_auth', '0002_remove_user_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='withdrawal_address',
            field=models.JSONField(blank=True, help_text='Stores complete withdrawal payment info.', null=True),
        ),
    ]
