# Generated by Django 5.2.4 on 2025-07-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_remove_causes_end_date_remove_causes_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='location',
        ),
    ]
