# Generated by Django 5.2.4 on 2025-07-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_id', 'status')},
        ),
    ]
