# Generated by Django 5.2.4 on 2025-07-31 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False, help_text='References the user ID from the user service')),
                ('cause_id', models.UUIDField(db_index=True, editable=False, help_text='References the cause ID from the cause service')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', help_text='Currency of the withdrawal amount', max_length=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paystack_transfer', 'Paystack Transfer')], default='bank_transfer', max_length=20)),
                ('payment_details', models.JSONField(help_text='Details of the payment account')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if the request fails', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the withdrawal request was made')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='When the withdrawal request was completed')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
