# Generated by Django 5.2.4 on 2025-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='entity_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
