# Generated by Django 5.2.4 on 2025-08-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_causes_rejection_reason_alter_causes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='rejection_reason',
        ),
    ]
