# Generated by Django 5.2.4 on 2025-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_remove_causes_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
